### ISSUE TITLE
Example without dagger

### ISSUE THREAD

**Issue by mohammedpascal** [glung/redux-java#14]
You have done a great job, I think if you provide examples without dagger this repo will fly

Dagger will just add complexity to people how don't know about it.

**Comment by glung** [comment]
Thank you. That's a great point. Those modules combined w/ the complexity of generics in Java are so hard to read. 

But I have to figure out the priorities for this repo though. I am in the process of deciding if I move it to Kotlin (already done in a branch) or Java8 and then update the examples accordingly.

**Comment by mohammedpascal** [comment]
I suggest to go with Java8.
Since it's redux-java should be pure java, likewise android examples should be pure android.

You can have separate repo for each language just like
https://github.com/ReactiveX
they have:

RxJava
RxKotlin
RxScala
..

Maybe you don't have time for all that but if you make it simple people will get the idea and jump in to help you.

**Comment by welkie** [comment]
+1 to the idea of a pure Java example. Personally, I've always learned best incrementally. I'm excited for Kotlin and some of the other tools we have to help with Android development, but it's hard to understand a new concept when you're first forced to understand a few other concepts that are new to you, especially if you don't particularly care about those other concepts.

**Comment by glung** [comment]
I agree with you!
I am going to mark this repo as deprecated.

I am following up here with others: https://github.com/jvm-redux/
Unfortunately, this is very WIP

**Comment by mattwelke** [comment]
Excited to see this project is still active. :) I'll be following there. I'm in search of some architecture for my Android apps since I'm sick of piling everything into the Activity and praying nothing breaks. I'm looking into MVP and it's helped a lot, but I plan on trying out this Redux style architecture too. In the new repo, I'd be happy to report back with what worked well or didn't for me, and post examples as I work.

**Comment by glung** [comment]
Hello, I am closing it. The new version (1.0) does not use Dagger (but may benefit from a more realistic example 😁). I am guessing it will come as part of https://github.com/jvm-redux/
